### ISSUE TITLE
replace lib/merge with a module

### ISSUE THREAD

**Issue by topa** [peerigon/alamid-schema#21]
Wouldn't it be much nicer to use a module for [merge.js](https://github.com/peerigon/alamid-schema/blob/master/lib/merge.js) instead of self-maintain this functionality?

A module would allow to drop merge.js + tests -> less maintenance.

**Comment by topa** [comment]
I think the same question is valid for [determineType.js](https://github.com/peerigon/alamid-schema/blob/master/lib/determineType.js).

**Comment by jhnns** [comment]
I did a quick research and tried some libraries: Couldn't find any that implements the current behavior. Although it is probably possible to find a library that fits, I think it's better to keep this logic inside alamid-schema, because this way we can control it.

Merging objects is not a trivial task because there are many ways how to solve conflicts. Since `merge.js` is rather small, I think it's good to keep that logic inside alamid-schema.
